### ISSUE TITLE
Italan?

### ISSUE THREAD

**Issue by jimlynnjulian** [Bbalduzz/Nexploix#1]
Perhaps you should explain the movie is downloaded with burned in Italian subtitles but with the original English audio.

**Comment by Bbalduzz** [comment]
mhh it shouldnt, I mean It could happen but it should be written. Can u tell me what title did u tried to download?

**Comment by jimlynnjulian** [comment]
I just tried a second title that downloaded with Italian audio. Seems some of the shows on that site remain in English and have subs burnt in. 

The title with burnt in subs is "The Banshees of Inisherin. The movie is a new movie and probably has not been dubbed yet.

The Ialian Netflix will not have the same movies as the US set, which I use. This would explain why I get a list of "close matches" when I enter some US titles. The 'Banshees' movie did have "Ita-sub" after the title.
If I enter the title "The Mask of Zorro", I get a list of alternatives that includes the 'Banshees movie:
https://www.netflix.com/watch/5670479?trackId=255824129&tctx=0%2C0%2CNAPA%40%40%7Cf152afa9-5d87-4b17-af5c-eec347e07291-914631244_titles%2F1%2F%2Fthe%20mask%20of%20zorro%2F0%2F0%2CNAPA%40%40%7Cf152afa9-5d87-4b17-af5c-eec347e07291-914631244_titles%2F1%2F%2Fthe%20mask%20of%20zorro%2F0%2F0%2Cunknown%2C%2Cf152afa9-5d87-4b17-af5c-eec347e07291-914631244%7C1%2C%2C

listing returned:
 0. [movie] The Mask 2 (HD)
    1. [tvshow] The Mask (HD)
    2. [movie] The Mask - Da zero a mito (2K)
    3. [movie] Behind the Mask - Vita di un Serial Killer (2K)
    4. [movie] The Seven Deadly Sins: Grudge of Edinburgh – Part 1 (2K)
x    5. [movie] The Banshees of Inisherin [Sub-Ita] (HD)
    6. [tvshow] The Sound of Magic (2K)
    7. [tvshow] The Guardians of Justice (2K)
    8. [tvshow] The Book of Boba Fett (4K)
    9. [movie] The Spine of Night (2K)
